= PlantUML encoding functions 

This repository exposes a PHP implementation of four *PlantUML encoding functions*:

* `encodep`
* `encode6bit`
* `append3bytes`
* `encode64`

Usually only `encodep` is used.

== Purpose

link:http://plantuml.com/[PlantUML] uses a *special encoding* to transform an uml text description like:

----
Bob -> Alice : hello
----

into this:

----
SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
----

The advantage of the last encoding is that it is easier to use in URL:

http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

To achieve such an encoding, the text diagram is:

* [line-through]#Underline text#
* Compressed using Deflate algorithm
* Encoded back in plain ASCII using a transformation close to base64


== Example

You must import `encodep` function before using it.

[source, php]
----
<?php
require 'vendor/autoload.php';

use function Jawira\PlantUml\encodep;

$encode = encodep('Alice -> Bob: hello');
echo "http://www.plantuml.com/plantuml/uml/{$encode}";
----

WARNING: Since v1.0.0, `encodep` function expects to receive utf8 text, therefore it doesn't encodes text to utf8 anymore.

More examples:

* link:ressources/examples/example-1.php[]
* link:ressources/examples/example-2.php[]

== Credits

These functions are a copy/paste from:

* http://plantuml.com/pte
* http://plantuml.com/code-php
