= PlantUML encoding functions 

[.lead]
This library exposes the PHP implementation of four *PlantUML encoding functions*:

* `encodep()`
* `encode6bit()`
* `append3bytes()`
* `encode64()`

Usually only `encodep()` is used.

image:https://poser.pugx.org/jawira/plantuml-encoding/v/stable[title="Latest Stable Version", link="https://packagist.org/packages/jawira/plantuml-encoding"]
image:https://poser.pugx.org/jawira/plantuml-encoding/license[title="License", link="https://packagist.org/packages/jawira/plantuml-encoding"]
image:https://poser.pugx.org/jawira/plantuml-encoding/composerlock[title="composer.lock", link="https://packagist.org/packages/jawira/plantuml-encoding"]

== Purpose

link:http://plantuml.com/[PlantUML] uses a *special encoding* to transform an
uml text description like this:

----
Bob -> Alice : hello
----

into this:

----
SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
----

The advantage of the last encoding is that it is easier to use in URL:

http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

== Install

Install using Composer:

[source, bash]
----
$ composer require jawira/plantuml-encoding
----

== Usage

You must import `encodep()` function before using it.

[source, php]
----
<?php
require 'vendor/autoload.php';

use function Jawira\PlantUml\encodep;

$encode = encodep('Alice -> Bob: hello');
echo "http://www.plantuml.com/plantuml/uml/{$encode}";
----

TIP: Only PHP 5.6+ allows importing functons, for versions < PHP 5.6 you have to
use full functin's namespace.

WARNING: Since v1.0.0, `encodep()` function expects to receive an UTF-8 string.

More examples:

* link:resources/examples/example-1.php[]
* link:resources/examples/example-2.php[]

== Credits

These functions are a copy/paste from link:http://plantuml.com/code-php[].
