name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        php: ['7.4','8.0','8.1','8.2','8.3','8.4']
    runs-on: ubuntu-24.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phing:v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: "ramsey/composer-install@v3"

      - name: Run tests
        run: phing -longtargets composer:validate tests:run phpstan:analyse
